openapi: 3.0.1
info:
  title: Retail API
  description: API description in OpenAPI 3.0 format
  version: 0.0.1

servers:
  - url: 'http://localhost:8085'

#TAGS
#=======================================================================================================================
tags:
  - name: Cart
    description: Cart related endpoints
  - name: Product
    description: Product related endpoints
  - name: Discount
    description: Discount related endpoints
#ENDPOINTS
#=======================================================================================================================
paths:
  /cart:
    post:
      tags:
        - Cart
      summary: Save cart
      operationId: saveCart
      description: Creation and saving cart
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Cart'
      responses:
        '204':
          description: Save command was successfully sent
        '400':
          $ref: '#/components/responses/BadRequestResponse'
        '409':
          $ref: '#/components/responses/ConflictResponse'

  /cart/{cartId}:
    post:
      tags:
        - Cart
      summary: Update cart
      operationId: updateCart
      description: Updating existing cart
      parameters:
        - $ref: '#/components/parameters/CartId'
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Cart'
      responses:
        '204':
          description: Update command was successfully sent
        '400':
          $ref: '#/components/responses/BadRequestResponse'
        '404':
          $ref: '#/components/responses/NotFoundResponse'
        '409':
          $ref: '#/components/responses/ConflictResponse'

  /cart/{cartId}/products:
    patch:
      tags:
        - Cart
      summary: Add product to cart
      operationId: addProductToCart
      description: Adding product to cart
      parameters:
        - $ref: '#/components/parameters/CartId'
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ProductItem'
      responses:
        '204':
          description: Update command was successfully sent
        '400':
          $ref: '#/components/responses/BadRequestResponse'
        '404':
          $ref: '#/components/responses/NotFoundResponse'
        '409':
          $ref: '#/components/responses/ConflictResponse'

  /cart/{cartId}/discounts:
    patch:
      tags:
        - Cart
      summary: Add discount to cart
      operationId: addDiscountToCart
      description: Adding discount to cart
      parameters:
        - $ref: '#/components/parameters/CartId'
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Discount'
      responses:
        '204':
          description: Update command was successfully sent
        '400':
          $ref: '#/components/responses/BadRequestResponse'
        '404':
          $ref: '#/components/responses/NotFoundResponse'
        '409':
          $ref: '#/components/responses/ConflictResponse'

    delete:
      tags:
        - Cart
      summary: Delete cart
      operationId: deleteCart
      description: Deleting cart
      parameters:
        - $ref: '#/components/parameters/CartId'
      responses:
        '204':
          description: Delete command was successfully sent
        '404':
          $ref: '#/components/responses/NotFoundResponse'
        '400':
          $ref: '#/components/responses/BadRequestResponse'

  /product:
    post:
      tags:
        - Product
      summary: Save product
      operationId: saveProduct
      description: Creation and saving product
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Product'
      responses:
        '204':
          description: Save command was successfully sent
        '400':
          $ref: '#/components/responses/BadRequestResponse'
        '409':
          $ref: '#/components/responses/ConflictResponse'

  /discount:
    post:
      tags:
        - Discount
      summary: Save Discount
      operationId: saveDiscount
      description: Creation and saving Discount
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Discount'
      responses:
        '204':
          description: Save command was successfully sent
        '400':
          $ref: '#/components/responses/BadRequestResponse'
        '409':
          $ref: '#/components/responses/ConflictResponse'

#COMPONENTS
#=======================================================================================================================
components:
  parameters:
    CartId:
      in: path
      name: cartId
      required: true
      schema:
        type: integer
        format: int64
        description: Id of the cart
      example: 111
    ProductId:
      in: path
      name: productId
      required: true
      schema:
        type: integer
        format: int64
        description: Id of the cart
      example: 111
    DiscountId:
      in: path
      name: productId
      required: true
      schema:
        type: integer
        format: int64
        description: Id of the cart
      example: 111

  #RESPONSES
  #=======================================================================================================================
  responses:
    NotFoundResponse:
      description: Not found
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/ErrorObject'
          example:
            status: 404
            title: Not Found
            detail: The requested resource was not found

    ConflictResponse:
      description: Conflict
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/ErrorObject'
          example:
            status: 409
            title: Conflict
            detail: The requested has conflict

    BadRequestResponse:
      description: Bad Request
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/ErrorObject'
          example:
            status: 400
            title: Bad Request
            detail: Invalid Request. Please, check the data in the request (QueryString Parameters and/or Body).

  #SCHEMAS
  #=======================================================================================================================
  schemas:
    Cart:
      title: object
      properties:
        id:
          type: integer
          format: int64
        products:
          type: array
          items:
            $ref: '#/components/schemas/ProductItem'
        discounts:
          type: array
          items:
            $ref: '#/components/schemas/Discount'

    ProductItem:
      type: object
      properties:
        productId:
          type: integer
          format: int64
        quantity:
          type: integer
          format: int32

    Discount:
      type: string

    Product:
      type: object
      properties:
        name:
          type: string
        cost:
          type: integer
          format: bigDecimal

    ErrorObject:
      type: object
      additionalProperties: false
      properties:
        status:
          type: integer
          description: Error code
          minimum: 100
          maximum: 599
        title:
          type: string
          description: Error title
          maxLength: 100
        detail:
          type: string
          description: Details of the exception

